## Vector
 * 물리학 용어
   * Scalar : 크기만 가지고 있는 물리량
   * Vector : 크기와 방향을 모두 가지고 있는 물리량
 * R에서의 vector : 값들의 집합(R에서는 Scalar인 하나의 숫자도 하나의 원소를 가진 Vector로 취급, Vector 안의 각 수치를 요소라고 함)
 * Vector의 특징
   * 벡터는 c()함수로 생성 : Combine Values into a Vector or List
   * 벡터의 인덱스는 1부터 시작
   * 하나의 벡터에는 하나의 자료형만 사용할 수 있음
   * 벡터에서 결측값(누락된 값)은 'NA(Not Available)'을 사용

In [1]:
1+2
# c함수 - 벡터를 만드는 함수
x <- c(1,2,3,4,5)
x
# rnorm : 정규분포 난수를 만드는 함수
xy <- rnorm(30)
xy

[1] 3

[1] 1 2 3 4 5

[1] -0.15260633  1.46935882  0.46631776 -1.31730411 -1.00393420  0.16896055
 [7] -0.50954107  1.88697078 -1.03349286 -0.75772685 -0.95765976  1.94299672
[13]  0.85124116  0.68827203  0.33536076  0.01842371 -0.74914994 -1.07718163
[19]  1.57614067  0.00456648  0.68510419  0.92843806  1.30621917 -0.42539660
[25]  0.58181187  1.79869625 -0.08426157  0.43382325 -0.03430425 -0.66717023

In [2]:
x
length(x) # 원소 갯수
mean(x) # 평균
range(x) # 범위
var(x) # 분산
sd(x) # 표준편차

[1] 1 2 3 4 5

[1] 5

[1] 3

[1] 1 5

[1] 2.5

[1] 1.581139

In [3]:
y <- c(2, 2, 3, 4, 4)
y
mean(y)
var(y)
sd(y)

[1] 2 2 3 4 4

[1] 3

[1] 1

[1] 1

In [4]:
x
x[2] # x의 두 번째 값
x[-2] # x의 두 번째 값을 제외한 나머지 요소들
x[3] <- 4 # x의 세 번째 값을 4로 변경
x

[1] 1 2 3 4 5

[1] 2

[1] 1 3 4 5

[1] 1 2 4 4 5

In [5]:
# 벡터 합치기
x <- c(3,6,9,12,15) # 벡터 생성
y <- c(5, 10, 15, 20, 25)
x
y
z <- append(x, y) # x에 y를 합친다
z

[1]  3  6  9 12 15

[1]  5 10 15 20 25

[1]  3  6  9 12 15  5 10 15 20 25

In [6]:
# 벡터형 자료의 연산 기능
c(1, 2) + c(4, 5) # 1+4, 2+5를 수행한다
c(1,2,3) + 1 # c에 1을 더한다
v <- -5:5 # -5에서 5까지 정수를 생성하여 할당한다
v

[1] 5 7

[1] 2 3 4

[1] -5 -4 -3 -2 -1  0  1  2  3  4  5

In [7]:
# seq() : Sequence Generation
q <- seq(from = 1, to = 5, by = 0.5) # 1부터 5까지 0.5 단위로 생성하여 할당한다
q
qq <- seq(10) # 1부터 10까지 생성하여 할당
qq

[1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0

[1]  1  2  3  4  5  6  7  8  9 10

In [8]:
x <- c(1,2,3)
y <- c(4,2,8)
x == y # x값과 y값이 같은지 순서에 따라 비교

[1] FALSE  TRUE FALSE

In [9]:
(x <- rep(c("a", "b", "c"), times=4)) # a,b,c,를 4번 반복하여 x를 생성
y <- unique(x) # 중복값 제거
y

[1] "a" "b" "c" "a" "b" "c" "a" "b" "c" "a" "b" "c"

[1] "a" "b" "c"

In [10]:
# 문자열 관련 함수
xx <- c("a", "b", "c", "d", "e") # 벡터 생성
xx
# 문자열 결합, 벡터 xx의 첫 번째와 두 번째 연결(공백으로 연결됨)
k = paste(xx[1], xx[2])
k

[1] "a" "b" "c" "d" "e"

[1] "a b"

In [11]:
# 문자열 결합(sep - 결합연산자)
paste("aaa", "bbb", "ccc", sep=",")
paste(x, collapse = "-") # 문자 사이에 -을 넣는다
paste(x, collapse = " ") # 문자 사이에 공백을 넣는다
substring("abcdefghijklmn", 2, 5) # 2에서 5까지의 문자열 뽑아내기

[1] "aaa,bbb,ccc"

[1] "a-b-c-a-b-c-a-b-c-a-b-c"

[1] "a b c a b c a b c a b c"

[1] "bcde"

In [12]:
# runif(갯수) : 0~1 사이의 난수 생성
# runif(갯수, 최솟값, 최댓값)

# 0 ~ 1 사이의 5개의 난수 생성
x <- runif(5)
x
y <- runif(5, 10, 20)
y
# x가 0.4 ~ 0.7 사이에 있는가?
(0.4 <= x) & (x <= 0.7)
# x 중에 0.9 이상이 있는가?
any(x >= 0.9)
# x의 값이 모두 0.9 이하인가?
all(x <= 0.9)
# x가 벡터형의 데이터인가?
is.vector(x)

[1] 0.73620191 0.10015086 0.80014547 0.19403692 0.08729778

[1] 18.54731 19.28993 19.24553 12.20924 16.67314

[1] FALSE FALSE FALSE FALSE FALSE

[1] FALSE

[1] TRUE

[1] TRUE

## 행렬
 * 2차원의 자료를 저장하는 자료형
 * rbind() : 행을 결합
 * cbind() : 컬럼을 결합

In [13]:
vec1 <- c(1, 2, 3)
vec2 <- c(4, 5, 6)
vec3 <- c(7, 8, 9)

# 행 결합(row bind) - 세로로 결합
mat1 <- rbind(vec1, vec2, vec3) # 행 결합
mat1

# 열 결합(column bind) - 가로로 결합
(mat2 <- cbind(vec1, vec2, vec3))

colnames(mat1) <- c("A", "B", "C") # 행렬 데이터 컬럼에 이름 할당
mat1

[,1] [,2] [,3]
vec1 1    2    3   
vec2 4    5    6   
vec3 7    8    9

vec1 vec2 vec3
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

A B C
vec1 1 2 3
vec2 4 5 6
vec3 7 8 9

In [14]:
# 데이터프레임 : 다양한 자료형을 모아서 구성된 행렬
# 벡터 선언
no <- c(1, 2, 3, 4)
name <- c("Apple", "Banana", "Peach", "Berry")
prices <- c(500, 200, 200, 50)
qty <- c(5, 2, 7, 9)

fruit <- data.frame(No=no, Name=name, Price=prices, QTY=qty)
fruit

# 데이터 프레임 데이터의 조작
# 데이터 프레임[행, 열]
fruit[1,] # 1번 행만 출력
fruit[, -2] # 2번 열을 제외하고 출력

No Name   Price QTY
1 1  Apple  500   5  
2 2  Banana 200   2  
3 3  Peach  200   7  
4 4  Berry   50   9

No Name  Price QTY
1 1  Apple 500   5

No Price QTY
1 1  500   5  
2 2  200   2  
3 3  200   7  
4 4   50   9

In [15]:
# 리스트 자료형
# list : key, value의 형태로 구성된 자료형
# (자바의 HashMap, 파이썬의 Dictionary와 비슷한 자료형)
member <- list(name = "김철수", address = "서울", tel = "010-2222-2222", pay = 360)
member

# 리스트 자료의 조작
member$name # name만 확인
# 1~3번 자료만 확인(숫자형 인덱스도 사용 가능, 4번 pay는 출력되지 않음)
member[1:3]
member$birth <- "1990-10-23" # 새로운 데이터의 삽입
member

$name
[1] "김철수"

$address
[1] "서울"

$tel
[1] "010-2222-2222"

$pay
[1] 360

[1] "김철수"

$name
[1] "김철수"

$address
[1] "서울"

$tel
[1] "010-2222-2222"

$name
[1] "김철수"

$address
[1] "서울"

$tel
[1] "010-2222-2222"

$pay
[1] 360

$birth
[1] "1990-10-23"

In [16]:
# 배열
# 3행 4열의 2차원 배열
array(1:12, dim=c(3,4))

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

In [17]:
x <- array(1:6, dim=c(3,2))
x
x[1, 1]
x[3, 2]
dim(x)

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[1] 1

[1] 6

[1] 3 2

In [18]:
# 자료형 판별
class(c(1, 2))
class(matrix(c(1, 2)))
class(list(c(1, 2)))
class(data.frame(x=c(1,2)))

[1] "numeric"

[1] "matrix"

[1] "list"

[1] "data.frame"

In [19]:
is.numeric(c(1, 2, 3))
is.numeric(c('a', 'b', 'c'))
is.matrix(matrix(c(1, 2)))

[1] TRUE

[1] FALSE

[1] TRUE